initial repo: pre-copy
git-svn-id: http://svn.tudos.org/repos/tudos/trunk@5 a704ac0b-3a55-4d43-a2a9-7be6f07c34fb

diff --git a/l4/Makefile b/l4/Makefile
--- a/l4/Makefile
+++ b/l4/Makefile
@@ -4,63 +4,174 @@
 # GLOBAL Makefile for the whole L4 tree
 #
 
-ifeq (${OSKIT_DIR},)
-  OSKITDIR = ../oskit
-else
-  OSKITDIR = ${OSKIT_DIR}
+L4DIR		?= .
+
+OSKITDIR	?= ../oskit
+OSKIT10DIR	?= ../oskit10
+
+BUILD_DIRS	= tool $(OSKITDIR) $(OSKIT10DIR) $(L4LINUX22_DIR) kernel pkg
+HELLODIRS	= pkg/l4sys \
+		  pkg/crtx \
+		  pkg/rmgr \
+		  pkg/l4util \
+		  pkg/oskit_support \
+		  pkg/sigma0 \
+		  pkg/hello
+install-dirs	= tool $(OSKITDIR) $(OSKIT10DIR) kernel pkg doc
+clean-dirs	= tool $(OSKITDIR) $(OSKIT10DIR) $(L4LINUX22_DIR) kernel pkg doc
+cleanall-dirs	= tool kernel pkg doc
+
+# our default target is all::
+all::
+
+#####################
+# config-tool
+
+DROPSCONF 		= y
+DROPSCONF_DEFCONFIG	= $(L4DIR)/mk/defconfig/config.x86
+DROPSCONF_CONFIG_IN	= $(L4DIR)/mk/config.in
+DROPSCONF_CONFIG	= $(L4DIR)/.Makeconf.bid
+DROPSCONF_CONFIG_H	= $(L4DIR)/include/l4/bid_config.h
+DROPSCONF_CONFIG_MK	= $(L4DIR)/.Makeconf.bid.converted
+DROPSCONF_DONTINC_MK	= y
+DROPSCONF_HELPFILE	= $(L4DIR)/mk/config.help
+
+# separation in "dependent" (ie opts the build output depends on) and
+# "independent" (ie opts the build output does not depend on) opts
+CONFIG_MK_INDEPOPTS	= DEPEND_VERBOSE_SWITCH DEPEND_VERBOSE VERBOSE_SWITCH \
+			  SHOWMESSAGES BID_COLORED_PHASES HAVE_LDSO \
+			  INT_CPP_NAME_SWITCH BID_LIBGENDEP INT_CPP_.*_NAME \
+			  INT_CXX_.*_NAME VERBOSE BID_STRIP_PROGS
+CONFIG_MK_REAL		= Makeconf.bid.local
+CONFIG_MK_INDEP		= Makeconf.bid.local.indep
+
+ifneq ($(filter help config txtconfig oldconfig,$(MAKECMDGOALS)),)
+# tweek $(L4DIR)/mk/Makeconf to use the intermediate file
+export BID_IGN_ROOT_CONF=y
+BID_ROOT_CONF=$(L4DIR)/.Makeconf.bid.converted
 endif
 
-SUBDIRS = pkg kernel 
-#doc
+# $(L4DIR)/mk/Makeconf shouln't include Makeconf.local twice
+MAKECONFLOCAL		= /dev/null
+include $(L4DIR)/mk/Makeconf
+export DROPS_STDDIR
 
-HELLODIRS =	pkg/l4sys/ \
-		pkg/l4util/ \
-		pkg/l4dbg/ \
-		pkg/crtx/ \
-		pkg/rmgr/ \
-		pkg/oskit_support/ \
-		pkg/sigma0/ \
-		pkg/hello/
+# after having absfilename, we can export BID_ROOT_CONF
+ifneq ($(filter config txtconfig oldconfig, $(MAKECMDGOALS)),)
+export BID_ROOT_CONF=$(call absfilename,$(L4DIR))/.Makeconf.bid.converted
+endif
 
-default: all
+#####################
+# rules follow
 
-all:: oskit
+# some dependencies
+all::	$(BUILD_DIRS) doc
+tool:	$(DROPSCONF_CONFIG_MK)
+pkg:	$(DROPSCONF_CONFIG_MK) tool $(OSKITDIR) $(OSKIT10DIR) $(L4LINUX22_DIR)
+doc:	pkgdoc
+kernel: $(DROPSCONF_CONFIG_MK) tool
 
-.PHONY: all clean cleanall
+tool pkg kernel:
+	$(VERBOSE)if [ -r $@/Makefile ]; then $(MAKE) -C $@; fi
 
-cleanall::
-	rm -f *~
+$(OSKITDIR) $(OSKIT10DIR) $(L4LINUX22_DIR): $(DROPSCONF_CONFIG_MK)
+	$(VERBOSE)if [ -r $@/Makefile.drops ]; then \
+		$(MAKE) -C $@ -f Makefile.drops; fi
 
-all clean cleanall::
-	for i in $(SUBDIRS) ; do \
-	    $(MAKE) -C $$i $@ ; \
-	  done
+doc:
+	$(VERBOSE)for d in tool doc ; do \
+		test ! -r $$d/Makefile || $(MAKE) -C $$d $@ ; done
 
-$(SUBDIRS):
-	$(MAKE) -C $@
+pkgdoc:
+	$(VERBOSE)test ! -r pkg/Makefile || $(MAKE) -C pkg doc
 
-# build 'Hello World' Server
-hello:	oskit
-	cd pkg && $(MAKE) pkg-links
-	set -e; for i in $(HELLODIRS) ; do \
+
+# 'Hello World' Server is special: It requires oskit to be present
+hello:	oskit.present $(OSKITDIR)
+	$(VERBOSE)set -e; for i in $(HELLODIRS) ; do \
 	  $(MAKE) -C $$i lib ; \
 	done
-	set -e; for i in $(HELLODIRS) ; do \
-	  $(MAKE) -C $$i ; \
+	$(VERBOSE)set -e; for i in $(HELLODIRS) ; do \
+	  test $$i = pkg/l4util || $(MAKE) -C $$i ; \
 	done
 
-# OSKIT rules
-
-.PHONY: oskit oskit.conf oskit.present $(SUBDIRS)
-
-oskit: oskit.present oskit.conf
-	cd $(OSKITDIR) && $(MAKE)
-
 oskit.present:
-	@cd $(OSKITDIR) || \
+	@test -r $(OSKITDIR)/Makefile.drops || \
 	  (echo "ERROR: please install OSKIT to $(OSKITDIR)"; exit 1)
 
-oskit.conf: $(OSKITDIR)/GNUmakefile
+.PHONY: all clean cleanall install hello oskit.present pkgdoc
+.PHONY: $(BUILD_DIRS) $(HELLODIRS) doc/html
 
-$(OSKITDIR)/GNUmakefile:
-	cd $(OSKITDIR) && ./configure
+cleanall::
+	$(VERBOSE)rm -f *~
+
+clean cleanall install::
+	$(VERBOSE)set -e; for i in $($@-dirs) ; do \
+	  if [ -r $$i/Makefile -o -r $$i/GNUmakefile ] ; then \
+		$(MAKE) -C $$i $@ ; fi ; done
+
+#####################
+# config-rules follow
+
+# it becomes a bit confusing now: 'make config' results in a config file, which
+# must be postprocessed. This is done in config.inc. Then,
+# we evaluate some variables that depend on the postprocessed config file.
+# The variables are defined in mk/Makeconf, which sources Makeconf.bid.local.
+# Hence, we have to 1) postprocess, 2) call make again to get the variables.
+DROPSCONF_CONFIG_MK_POST_HOOK::
+        # try-libgendep must be done before calling make with the local helper
+	$(VERBOSE)$(MAKE) try-libgendep
+	$(VERBOSE)$(MAKE) Makeconf.bid.local-helper || \
+		(rm -f $(DROPSCONF_CONFIG_MK) $(CONFIG_MK_REAL) $(CONFIG_MK_INDEP); false)
+
+# cashing of some variables. Others are determined directly.
+# The contents of the variables to cache is already defined in mk/Makeconf.
+.PHONY: Makeconf.bid.local-helper try-libgendep
+ARCHS = $(BUILD_SYSTEMS_x86) $(BUILD_SYSTEMS_arm)
+Makeconf.bid.local-helper:
+	$(foreach arch,$(ARCHS),$(if $(CPU_$(arch)),, \
+	    $(error Specify at least one CPU-type for architecture "$(arch)")))
+	$(VERBOSE)echo BUILD_SYSTEMS="$(strip				\
+	    $(foreach arch, $(ARCHS), $(foreach cpu,$(CPU_$(arch)),	\
+		$(foreach l4api, l4v2 l4x0 l4x2 l4v4,			\
+		    $(if $(filter y,$(BUILD_SYSTEMS_$(arch)_$(l4api))),	\
+			$(arch)_$(cpu)-$(l4api)))			\
+		    $(arch)_$(cpu) )))" >>$(DROPSCONF_CONFIG_MK)
+	$(VERBOSE)$(foreach arch, $(ARCHS), \
+		$(foreach v, GCCDIR GCCLIB GCCLIB_EH GCCVERSION,\
+			echo $(v)_$(arch)=$(call $(v)_f,$(arch)) \
+			>>$(DROPSCONF_CONFIG_MK);))
+	$(foreach v, BID_LIBGENDEP, echo $v=$($(v)) >>$(DROPSCONF_CONFIG_MK);)
+	$(VERBOSE)echo 'BUILD_PIC += $$(BUILD_LOADER_PICS)' >>$(DROPSCONF_CONFIG_MK)
+ifeq ($(INT_CPP_NAME_SWITCH), y)
+	$(VERBOSE)$(foreach arch, $(ARCHS), \
+		set -e; X=`tempfile -s .c` ; echo 'int main(void){}'>$$X ; \
+		rm -f $$X.out ; LD_PRELOAD=$(BID_LIBGENDEP) GENDEP_SOURCE=$$X \
+		GENDEP_OUTPUT=$$X.out $(CC_$(arch)) -c $$X -o $$X.o; \
+		test -e $$X.out; echo INT_CPP_$(arch)_NAME=`cat $$X.out` \
+			>>$(DROPSCONF_CONFIG_MK); )\
+		rm -f $$X $$X.{c,out}
+	$(VERBOSE)$(foreach arch, $(ARCHS), \
+		set -e; X=`tempfile -s .cc` ; echo 'int main(void){}'>$$X; \
+		rm -f $$X.out; LD_PRELOAD=$(BID_LIBGENDEP) GENDEP_SOURCE=$$X \
+		GENDEP_OUTPUT=$$X.out $(CXX_$(arch)) -c $$X -o $$X.o; \
+		test -e $$X.out; echo INT_CXX_$(arch)_NAME=`cat $$X.out` \
+			>>$(DROPSCONF_CONFIG_MK) ; ) \
+		rm -f $$X $$X.{cc,out}
+endif
+	$(VERBOSE)sort <$(DROPSCONF_CONFIG_MK) >$(CONFIG_MK_REAL).tmp
+	$(VERBOSE)echo -e "# Automatically generated. Don't edit\n" >$(CONFIG_MK_INDEP)
+	$(VERBOSE)grep $(addprefix -e ^,$(CONFIG_MK_INDEPOPTS) ) \
+		<$(CONFIG_MK_REAL).tmp >>$(CONFIG_MK_INDEP)
+	$(VERBOSE)echo -e "# Automatically generated. Don't edit\n" >$(CONFIG_MK_REAL).tmp2
+	$(VERBOSE)grep -v $(addprefix -e ^,$$ # $(CONFIG_MK_INDEPOPTS) ) \
+		<$(CONFIG_MK_REAL).tmp >>$(CONFIG_MK_REAL).tmp2
+	$(VERBOSE)echo -e 'include $(call absfilename,$(CONFIG_MK_INDEP))' >>$(CONFIG_MK_REAL).tmp2
+	$(VERBOSE)diff --brief $(CONFIG_MK_REAL) $(CONFIG_MK_REAL).tmp2 || \
+		mv $(CONFIG_MK_REAL).tmp2 $(CONFIG_MK_REAL)
+	$(VERBOSE)$(RM) $(CONFIG_MK_REAL).tmp $(CONFIG_MK_REAL).tmp2
+
+# If a local libgendep is here, use it. Otherwise, the build process will
+# utilize the global one; or fail if this is not available too.
+try-libgendep:
+	$(VERBOSE)test ! -r tool/gendep/Makefile || $(MAKE) -C tool/gendep
diff --git a/l4/pkg/Makefile b/l4/pkg/Makefile
--- a/l4/pkg/Makefile
+++ b/l4/pkg/Makefile
@@ -9,32 +9,55 @@ include $(L4DIR)/mk/Makeconf
 # like this unless you really know what you are doing, as opposed to me.
 libstdc++.headers: libstdc++.lib
 
-# dm_phys uses IDLs of dm_mem
-dm_phys.headers: dm_mem.headers
-# dm_mem uses IDLs of dm_generic
-dm_mem.headers: dm_generic.headers
-# bootmod uses IDLs of dm_generic
-bootmod.headers: dm_generic.headers
-# IDL of qos_rmgr uses headers of qos_mgr
-qos_rmgr.headers: qos_mgr.headers
+# other (mostly IDL-related) dependencies
+bootmod.headers:	dm_generic.headers
+l4util.lib:		rmgr.headers rmgr.lib
+con.headers:		l4sys.headers dm_generic.headers
+dm_generic.headers:	l4sys.headers l4env.headers
+dm_mem.headers:		dm_generic.headers
+dm_phys.headers:	dm_mem.headers
+semaphore.headers:	l4sys.headers l4util.headers l4env.headers thread.headers
+thread.headers:		l4sys.headers l4env.headers
+dsi_example.headers:	l4sys.headers
+dsi_staticfs.headers:	l4sys.headers
+dsitest_receiver.headers: l4sys.headers
+dsitest_sender.headers:	l4sys.headers
+exec.headers:		l4sys.headers dm_generic.headers
+generic_blk.headers:	l4sys.headers semaphore.headers dm_generic.headers
+generic_fprov.headers:	l4sys.headers dm_generic.headers
+loader.headers:		l4sys.headers dm_generic.headers
+qos_mgr.headers:	l4sys.headers
+qos_quota.headers:	qos_mgr.headers
+qos_rmgr.headers:	qos_mgr.headers
+qos_user.headers:	l4sys.headers
+loader.lib:		bootmod.lib con.lib dm_generic.lib dm_mem.lib \
+			generic_ts.lib l4env.lib l4rm.lib l4util.lib log.lib \
+			names.lib rmgr.lib semaphore.lib slab.lib thread.lib
+usb.bin:		dope.bin
 
 # The directories/packages of l4env
 L4ENV_SUBDIRS = \
 	bootmod \
 	buffermgr \
+	con \
 	crtx \
+	cxx \
 	dm_generic \
 	dm_mem \
 	dm_phys \
+	exec \
 	generic_blk \
 	generic_fprov \
 	generic_io \
 	generic_ts \
+	input \
 	l4env \
+	linux-24-headers \
 	l4io \
 	l4rm \
 	l4sys \
 	l4util \
+	loader \
         lock \
 	log \
 	names \
@@ -59,10 +82,8 @@ L4CONF_FILES = 				\
 	Makeconf.flick			\
 	Makeconf.lib.rules		\
 	Makeconf.lib.targets		\
-	Makeconf.oskit10_l4env		\
-	Makeconf.oskit10_l4env_tiny	\
 	Makeconf.stdtargets		\
-	Makeconf.transitional		\
+	Makefile
 
 BID_STATE_FILE = BUILD.state
 
@@ -84,6 +105,11 @@ L4ENV_BUILD_SUBDIRS = $(filter $(L4ENV_SUBDIRS), $(BUILD_SUBDIRS))
 PKG_MAKEFILE_SYMLINKS=$(addsuffix /Makefile,$(BUILD_SUBDIRS) $(OBSOLETE_SUBDIRS))
 
 #####################
+# Rules begin.
+# We start with cont-checking, as this requires special treatment
+ifeq ($(filter cont,$(MAKECMDGOALS)),)
+
+#####################
 # default make action is "all" - build all packages
 #
 # We build all l4env headers (idl+includes), then all l4env libs, then the
@@ -91,6 +117,7 @@ PKG_MAKEFILE_SYMLINKS=$(addsuffix /Makefile,$(BUILD_SUBDIRS) $(OBSOLETE_SUBDIRS)
 # (idl+includes), the other libs, the other servers and examples. We use
 # dependencies for this, witch might allow parallel build processes.
 #
+
 all::		bin
 bin:		lib
 lib:		headers
@@ -98,106 +125,165 @@ headers:	l4env
 l4env:		l4env-lib
 l4env-lib:	l4env-headers
 
-bin:		$(addsuffix .bin,$(filter-out $(L4ENV_SUBDIRS),$(BUILD_SUBDIRS)))
-lib:		$(addsuffix .lib,$(filter-out $(L4ENV_SUBDIRS),$(BUILD_SUBDIRS)))
-headers:	$(addsuffix .headers,$(filter-out $(L4ENV_SUBDIRS),$(BUILD_SUBDIRS)))
-l4env:		$(addsuffix .bin,$(L4ENV_BUILD_SUBDIRS))
-l4env-lib:	$(addsuffix .lib,$(L4ENV_BUILD_SUBDIRS))
-l4env-headers:	$(addsuffix .headers,$(L4ENV_BUILD_SUBDIRS))
+TGT_bin		:= $(addsuffix .bin,$(filter-out $(L4ENV_SUBDIRS),$(BUILD_SUBDIRS)))
+TGT_lib		:= $(addsuffix .lib,$(filter-out $(L4ENV_SUBDIRS),$(BUILD_SUBDIRS)))
+TGT_headers	:= $(addsuffix .headers,$(filter-out $(L4ENV_SUBDIRS),$(BUILD_SUBDIRS)))
+TGT_l4env	:= $(addsuffix .bin,$(L4ENV_BUILD_SUBDIRS))
+TGT_l4env-lib	:= $(addsuffix .lib,$(L4ENV_BUILD_SUBDIRS))
+TGT_l4env-headers:=$(addsuffix .headers,$(L4ENV_BUILD_SUBDIRS))
+
+bin:			$(TGT_bin)
+lib $(TGT_bin):		$(TGT_lib)
+headers $(TGT_lib): 	$(TGT_headers)
+l4env $(TGT_headers): 	$(TGT_l4env)
+l4env-lib $(TGT_l4env):	$(TGT_l4env-lib)
+l4env-headers $(TGT_l4env-lib): $(TGT_l4env-headers)
+$(TGT_l4env-headers):	rm-old-links
 
 #####################
 # cont handling
-ifeq ($(filter cont,$(MAKECMDGOALS)),)
-BID_reset = reset
-else
 -include $(BID_STATE_FILE)
-endif
-reset:
+BID_cont_reset:
 	$(VERBOSE)$(RM) $(BID_STATE_FILE)
-cont:
-	$(VERBOSE)$(MAKE) $(addprefix -o ,reset $(BID_STATE_DONE))
 BID_SAFE_STATE= @echo 'BID_STATE_DONE+=$@'>>$(BID_STATE_FILE)
 
-.PHONY: all reset cont bin lib headers idl include
+.PHONY: all BID_cont_reset cont bin lib headers idl include doc
 .PHONY: l4env l4env-lib l4env-headers l4env-include l4env-idl
+.PHONY: rm-old-links
 
-ifeq "$(SHOWMESSAGES)" "true"
-BIN_MESSAGE=@echo "=== Building servers, examples, doc of \"$(basename $@)\" ==="
-LIB_MESSAGE=@echo "=== Building lib of \"$(basename $@)\" ==="
+ifneq ($(filter true y,$(SHOWMESSAGES)),)
+BIN_MESSAGE=@echo "=== Building servers, examples of \"$(basename $@)\" ==="
+DOC_MESSAGE=echo "=== Creating documentation for package \"$(1)\" ==="
 HDR_MESSAGE=@echo "=== Building IDL & includes of \"$(basename $@)\" ==="
 INST_MESSAGE=echo "=== Installing Package \"$(1)\" ==="
-TEMPLATE_MESSAGE=@echo "=== Creating symlinks to Makefile template in $(@D) ==="
+LIB_MESSAGE=@echo "=== Building lib of \"$(basename $@)\" ==="
+PURGE_INC_MESSAGE=@echo "=== Purging pending links in $(L4DIR)/include ==="
+PURGE_LIB_MESSAGE=@echo "=== Purging pending links in $(L4DIR)/lib ==="
+TEMPLATE_MESSAGE=echo "=== Creating symlinks to Makefile template in $(@D) ==="
+UPDATE_MESSAGE=echo "=== Updating \"$(1)\" ==="
+else
+# bash has problems with empty '; ;' sequences
+BIN_MESSAGE=true
+DOC_MESSAGE=true
+HDR_MESSAGE=true
+INST_MESSAGE=true
+LIB_MESSAGE=true
+PURGE_INC_MESSAGE=true
+PURGE_LIB_MESSAGE=true
+UPDATE_MESSAGE=true
+TEMPLATE_MESSAGE=true
 endif
 
-$(addsuffix .bin,$(BUILD_SUBDIRS)):%.bin:%/Makefile $(BID_reset)
+$(addsuffix .bin,$(BUILD_SUBDIRS)):%.bin:%/Makefile BID_cont_reset
 	$(BIN_MESSAGE)	
 	$(VERBOSE)$(MAKE) -C $(basename $@) all -o lib -o include -o idl
 	$(VERBOSE)$(BID_SAFE_STATE)
 
-$(addsuffix .lib,$(BUILD_SUBDIRS)):%.lib:%/Makefile $(BID_reset)
+$(addsuffix .lib,$(BUILD_SUBDIRS)):%.lib:%/Makefile BID_cont_reset
 	$(LIB_MESSAGE)
 	$(VERBOSE)$(MAKE) -C $(basename $@) lib -o include -o idl
 	$(VERBOSE)$(BID_SAFE_STATE)
 
-$(addsuffix .headers,$(BUILD_SUBDIRS)):%.headers:%/Makefile $(BID_reset)
+$(addsuffix .headers,$(BUILD_SUBDIRS)):%.headers:%/Makefile BID_cont_reset
 	$(HDR_MESSAGE)
 	$(VERBOSE)$(MAKE) -C $(basename $@) idl
 	$(VERBOSE)$(BID_SAFE_STATE)
 
 install:: $(PKG_MAKEFILE_SYMLINKS)
 	$(VERBOSE)set -e; for i in $(BUILD_SUBDIRS); do \
-	  $(call INST_MESSAGE,$$$$i); \
+	  $(call INST_MESSAGE,$(BID_DOLLARQUOTE)$$i); \
+	  $(MAKE) -C $$i $@; \
+	done
+
+doc: $(PKG_MAKEFILE_SYMLINKS)
+	$(VERBOSE)set -e; for i in $(BUILD_SUBDIRS); do \
+	  $(call DOC_MESSAGE,$(BID_DOLLARQUOTE)$$i); \
 	  $(MAKE) -C $$i $@; \
 	done
 
 .PHONY: $(foreach ext, .bin .lib .include .idl .headers,addsuffix $(ext), $(BUILD_SUBDIRS))
 
-clean cleanall:: $(BID_reset)
+clean cleanall:: BID_cont_reset
 clean cleanall::
-	@for i in $(BUILD_SUBDIRS) $(OBSOLETE_SUBDIRS); do \
+	$(VERBOSE)$(RM) update.log
+	$(VERBOSE)for i in $(BUILD_SUBDIRS) $(OBSOLETE_SUBDIRS); do \
 	  echo "=== Cleaning in package  \"$$i\" ==="; \
 	  if [ -r $$i/Makefile ] ; then $(MAKE) -C $$i $@; fi ; \
 	done
+	$(VERBOSE)$(MAKE) rm-old-links
 
 del-backup:
-	@rm -i `find . -name "*~"` `find . -name "#*#"`
+	$(VERBOSE)rm -i `find . -name "*~"` `find . -name "#*#"`
 
 pkg-links: $(PKG_MAKEFILE_SYMLINKS)
 
 $(PKG_MAKEFILE_SYMLINKS):
-	$(TEMPLATE_MESSAGE)
-	$(LN) -s ../pkg.Makefile.tmpl $@
+	$(VERBOSE)$(TEMPLATE_MESSAGE)
+	$(VERBOSE)$(LN) -s ../pkg.Makefile.tmpl $@
+
+rm-old-links:
+	$(PURGE_INC_MESSAGE)
+	$(VERBOSE)test ! -d $(L4DIR)/include || find $(L4DIR)/include -type l -a ! -xtype f -a ! -xtype d -exec rm -v '{}' ';'
+	$(PURGE_LIB_MESSAGE)
+	$(VERBOSE)test ! -d $(L4DIR)/lib || find $(L4DIR)/lib -type l -a ! -xtype f -a ! -xtype d -exec rm -v '{}' ';'
 
 rm-pkg-links:
-	$(VERBOSE)$(RM) -i `find -mindepth 2 -maxdepth 2 -type l -name "Makefile"`
+	$(VERBOSE)find -mindepth 2 -maxdepth 2 -type l -name Makefile -exec $(RM) -i '{}' ';'
 
 rm-pkg-links-force:
-	$(VERBOSE)$(RM) `find -mindepth 2 -maxdepth 2 -type l -name "Makefile"`
+	$(VERBOSE)find -mindepth 2 -maxdepth 2 -type l -name Makefile -exec $(RM) '{}' ';'
 
 
 # Update Makefile on l4env_update.
-ifneq ($(filter l4env_update,$(MAKECMDGOALS)),)
+ifneq ($(filter l4env_update update,$(MAKECMDGOALS)),)
 .PHONY: Makefile
-Makefile:
-	cvs up $@
+Makefile: update.log
+	cvs up $@ 2>&1 | tee -a update.log
 endif
 
-l4env_update: l4conf_update gcc-wrap_update $(BID_reset)
-	for i in $(L4ENV_SUBDIRS); do \
-	  echo "=== Updating \"$$i\" ==="; \
-	  cvs update -d $$i; \
+.PHONY: update.log
+update.log:
+	$(VERBOSE)$(RM) $@
+
+l4env_update: l4conf_update gcc-wrap_update dice_update BID_cont_reset update.log
+	$(VERBOSE)set -e; for i in $(L4ENV_SUBDIRS); do \
+	  if [ "$$i" != linux-24-headers -o -d $$i -o \( "$(LINUX24_AVAIL)" = "n" -a "$(LINUX24_GLOBALINC)" = "n" \) ] ; then \
+	    $(call UPDATE_MESSAGE,$(BID_DOLLARQUOTE)$$i); \
+	    cvs -q update -d $$i 2>&1 | tee -a update.log; \
+	  fi; \
 	done
-	cvs update pkg.Makefile.tmpl
+	cvs update pkg.Makefile.tmpl | tee -a update.log
+
+update: l4env_update update.log
+	$(VERBOSE)set -e ; \
+	  for i in $(filter-out $(L4ENV_SUBDIRS),$(ALL_SUBDIRS)) ; do \
+	    $(call UPDATE_MESSAGE,$(BID_DOLLARQUOTE)$$i); \
+	    cvs -q update -d $$i 2>&1 | tee -a update.log; done
 
 gcc-wrap:
 	$(VERBOSE)$(MAKE) -C $(L4DIR)/tool/gcc-wrap
 
-gcc-wrap_update:
-	$(VERBOSE)cd $(L4DIR) && cvs update -d tool/gcc-wrap
+gcc-wrap_update: update.log
+	$(VERBOSE)if [ -d $(L4DIR)/tool/gcc-wrap ] ; then \
+		$(call UPDATE_MESSAGE,l4/tool/gcc-wrap); \
+		cd $(L4DIR) && \
+		cvs -q update -d tool/gcc-wrap 2>&1 | tee -a update.log; \
+	fi
 
-l4conf_update:
-	set -e; \
-	( cd ..; cvs update $(L4CONF_FILES) )
+dice_update: update.log
+	$(VERBOSE)if [ -d $(L4DIR)/tool/dice ] ; then \
+		$(call UPDATE_MESSAGE,l4/tool/dice); \
+		cd $(L4DIR) && \
+		cvs -q update -d tool/dice 2>&1 | tee -a update.log; \
+	fi
+
+l4conf_update: update.log
+	@$(call UPDATE_MESSAGE,l4/Make{confs/files})
+	$(VERBOSE)cd .. && \
+		cvs -q update $(L4CONF_FILES) 2>&1 | tee -a update.log
+	@$(call UPDATE_MESSAGE,l4/mk/)
+	$(VERBOSE)cd ../mk && \
+		cvs -q update -d 2>&1 | tee -a update.log
 
 relocate:
 	@for i in $(BUILD_SUBDIRS); do 					\
@@ -211,19 +297,23 @@ relocate:
 
 relink:
 	@for i in $(BUILD_SUBDIRS); do 					\
-	     if [ -f $$i/server/src/Makefile ]; then			\
+	     if [ -f $$i/server/Makefile ]; then			\
 	       echo "=== Re-linking \"$$i\" server ===";		\
-	       $(MAKE) -C $$i/server/src;				\
+	       $(MAKE) -C $$i/server relink;				\
 	     else			 				\
-	       echo "( Package \"$$i\" has no server/src dir )"; 	\
+	       echo "( Package \"$$i\" has no server dir )"; 	\
 	     fi;							\
 	     if [ -f $$i/examples/Makefile ]; then			\
 	       echo "=== Re-linking \"$$i\" examples ===";		\
-	       $(MAKE) -C $$i/examples;					\
+	       $(MAKE) -C $$i/examples relink;				\
 	     else							\
 	       echo "( Package \"$$i\" has no examples dir )";		\
 	     fi;							\
 	 done;								\
+
+# global defines
+
+.PHONY:		install clean cleanall kernels
 
 
 print-subdirs:
@@ -234,33 +324,47 @@ help:
 	@echo "Specify one of the following targets:"
 	@echo "all             - build the l4env and the packages neither broken nor obsolete"
 	@echo "cont            - after correcting errors, continue where \"make all\" failed"
+	@echo "doc             - build documentation (not build per default)"
 	@echo "install         - install the packages, use only after making all!"
+	@echo
 	@echo "clean           - clean the packages"
 	@echo "cleanall        - clean the packages pedanticly"
 	@echo "del-backup      - remove temporary file in this tree"
-	@echo "pkg-links       - create symlinks to pkg.Makefile template in all subdirs"
-	@echo "rm-pkg-links    - delete symlinked Makefiles in the subdirs interactively"
-	@echo "rm-pkg-links-force - dito, non-interactively"
 	@echo "headers         - short for includes + idl"
 	@echo "idl             - generate IDLs in the subdirs and link them to the L4DIR"
 	@echo "includes        - link the includes in the subdirs to the L4DIR"
 	@echo "lib             - generate the libraries in the subdirs and link them"
+	@echo "l4conf_update   - cvsupdate the diverse Makeconf.* in the L4DIR"
+	@echo "l4env           - build the l4env"
 	@echo "l4env-headers   - headers target for the L4ENV dirs"
 	@echo "l4env-idl       - idl target for the L4ENV dirs"
 	@echo "l4env-include   - include target for the L4ENV dirs"
 	@echo "l4env-lib       - lib target for the L4ENV dirs"
-	@echo "l4env           - build the l4env"
 	@echo "l4env_update    - cvsupdate of the L4ENV dirs"
-	@echo "l4conf_update   - cvsupdate the diverse Makeconf.* in the L4DIR"
-	@echo "relocate        - building the relocatable binaries in the dirs"
-	@echo "relink          - rebuild servers and examples"
-	@echo "reset           - reset the state used by the \"cont\" target"
+	@echo "pkg-links       - create symlinks to pkg.Makefile template in all subdirs"
 	@echo "print-subdirs   - print the SUBDIRS which are subject to build"
+	@echo "relink          - rebuild servers and examples"
+	@echo "relocate        - building the relocatable binaries in the dirs"
+	@echo "reset           - reset the state used by the \"cont\" target"
+	@echo 'rm-old-links    - remove invalid symlinks in $$(L4DIR)/lib, $$(L4DIR)/include'
+	@echo "rm-pkg-links    - delete symlinked Makefiles in the subdirs interactively"
+	@echo "rm-pkg-links-force - dito, non-interactively"
+	@echo "update          - update l4env + the packages currently checked out"
 	@echo "help            - this help"
 	@echo -e "\nWhen building, you can omit sub-targets using the \"-o <tgt>\" switch to make."
 	@echo "\"make -o l4env\" skips rebuilding the l4env, \"make -o lib\" only builds"
 	@echo "binaries and examples."
 
-# global defines
+#####################
+# cont handling: "cont" is in the target list
+else
+-include $(BID_STATE_FILE)
+cont:
+	$(VERBOSE)$(MAKE) $(addprefix -o ,BID_cont_reset $(BID_STATE_DONE)) \
+		$(filter-out cont,$(MAKECMDGOALS))
 
-.PHONY:		install clean cleanall kernels
+# eat up the other targets
+.DEFAULT:
+	@true
+endif 
+
