update: pre-copy
git-svn-id: http://svn.tudos.org/repos/tudos/trunk@133 a704ac0b-3a55-4d43-a2a9-7be6f07c34fb

diff --git a/dice/bootstrap b/dice/bootstrap
--- a/dice/bootstrap
+++ b/dice/bootstrap
@@ -12,6 +12,7 @@ PACKAGE=dice
 
 AUTOMAKE_FLAGS="--add-missing --foreign"
 LIBTOOL_FLAGS="--force"
+LIBTOOL_DIR=libltdl
 
 automake_min_vers_maj=1
 automake_min_vers_min=9
@@ -170,9 +171,9 @@ lt_version=`$lt --version 2>/dev/null|head -1|sed -e 's/^.* \([0-9]\+\.[0-9]\+\.
 if test -z "$lt_version"; then
 	echo $lt: command not found
 	echo
-	echo "$ARGV0: WARNING: It is recommended to have \`libtoolize' installed to compile $PACKAGE."
+	echo "$ARGV0: ERROR: You must have \`libtoolize' installed to compile $PACKAGE."
 	echo "          (version $libtool_min_vers_maj.$libtool_min_vers_min or newer is required)"
-	lt=
+	exit 1;
 fi
 IFS=.; set $lt_version; IFS=' '
 if test "$1" = "$libtool_min_vers_maj" -a "$2" -lt "$libtool_min_vers_min" || test "$1" -lt "$libtool_min_vers_maj"; then
@@ -189,9 +190,13 @@ do_cmd() {
 	$@
 }
 
-if test -n "$lt"; then
-	do_cmd $lt $LIBTOOL_FLAGS
+if ! test -d $LIBTOOL_DIR; then
+	echo
+	echo "$ARGV0: WARNING: libltdl directory is missing."
+	echo "        Try to install from local version."
+	LIBTOOL_DLAGS=$LIBTOOL_FAGS --ltdl -c
 fi
+do_cmd $lt $LIBTOOL_FLAGS
 
 do_cmd $acl $ACLOCAL_FLAGS
 
@@ -200,6 +205,21 @@ do_cmd $ah
 do_cmd $am $AUTOMAKE_FLAGS
 
 do_cmd $ac
+
+# also run auto* tools in libtool subdir to have consistent configurations
+
+if test -d $IBTOOL_DIR; then
+	echo "$ARGV0: running autotools in subdir $LIBTOOL_DIR ..."
+	cd $LIBTOOL_DIR
+
+	do_cmd $acl $ACLOCAL_FLAGS
+	do_cmd $ah
+	do_cmd $am $AUTOMAKE_FLAGS
+	do_cmd $ac
+
+	cd -
+	echo "$ARGV0: done in subdir $LIBTOOL_DIR."
+fi
 
 cd $ORIGDIR || exit 1
 
